### ISSUE TITLE
Doesn't seem to work for child components

### ISSUE THREAD

**Issue by harvanchik** [farengeyt451/ngx-tippy-wrapper#13]
**Environment**

Angular version: 11.2.10

TypeScript version: 4.1.5

**Describe the bug**
Using the tippy service to `setContent()` does not work for components that are children of of parent component.  The console throws an error saying that it cannot find the identifier; however, if I move the element that I put the tippy on to the parent component, then it works.

**To Reproduce**
1. Create a component (A).  Create another component (B)
2. In Component A, add element of Component B (i.e. <app-component></app-component>
3. Add `ngxTippy tippyName="tip-id"` in an element in Comp. B's HTML.
4. Import Tippy service and trying setting content of that tippy from Comp. B TypeScript file. `this.tippyService.setContent('last-tip-id', 'test');`
5. Observe error in console.

**Expected behavior**
The tippy service should be searching the child component's HTML for the identifier, not the parent component's HTML.

**Screenshots**
![image](https://user-images.githubusercontent.com/66141166/115180642-f74ece00-a08a-11eb-9f1b-bfa301deece7.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome/Brave
 - Version latest

**Comment by farengeyt451** [comment]
Hi @harvanchik. Unfortunately, I am not fully understand you. 

Do you try use tippy like this?

```html
<component-a>

  <component-b  ngxTippy tippyName="tip-id"></component-b>
  
</component-a>
```

and then form `component-b.ts`

```ts
tippyService.setContent('tip-id', 'test');
```

Can you recreate problem on `codesandbox` or write template example here?

**Comment by harvanchik** [comment]
It's almost what you're saying, but `ngxTippy tippyName="tip-id"` is not in the `<component-b>` element itself, but within the template of component B.

**Comp. A Template**
```html
<component-a>

  <component-b></component-b>
  
</component-a>
```

**Comp. B Template**
```html
<span ngxTippy tippyName="tip-id"></span>
```

**Comp. B Typescript**
```typescript
tippyService.setContent('tip-id', 'test');
```

**Comment by farengeyt451** [comment]
@harvanchik you should use `setContent()` method on `ngAfterViewInit` lifecycle hook or later. Or, if you want use `ngOnInit` - defer `setContent` on next  event loop tick, i.e. using `setTimeout`. This is because service writes directives to store on `ngOnInit`

Exaple from docs:

```ts
...
import { NgxTippyService } from 'ngx-tippy-wrapper';

@Component({ ... })
export class DemoComponent implements OnInit, AfterViewInit {
  bindedContent: string = 'Binded tooltip content';

  constructor(private tippyService: NgxTippyService) {}

  ...

  ngAfterViewInit() {
    this.setContentForTooltip();
  }

  setContentForTooltip() {
    this.tippyService.setContent('content', this.bindedContent);
  }
}
```

**Comment by harvanchik** [comment]
Ah, okay. I'll try that out later.

**Comment by harvanchik** [comment]
That sort of did the trick but in addition to putting it in the `ngAfterViewInit()` I had to delay it by a second using `setTimeout()`.  I really do not know why.
