### ISSUE TITLE
Tippy directive is not destroyed causing a memory leak

### ISSUE THREAD

**Issue by bjarketrux** [farengeyt451/ngx-tippy-wrapper#17]
**Environment**

Angular version: 11
TypeScript version: 4.1.5

**Describe the bug**
Tippy directive is not destroyed causing a memory leak

**To Reproduce**
1. Go to https://angular-ngx-tippy-wrapper-memory-leak.stackblitz.io/
2. Press 'Toggle shown' button to hide/show 'Button with tooltip' a couple of times
3. In Google Chrome press F12 and make a memory snapshot. Search for 'tippy' in 'Class filter'.
4. Observe: that the NgxTippyDirective has as many instances as the button was toggled.

**Expected behavior**
Only one instance. The old ones should be destroyed.

**Screenshots**
![image](https://user-images.githubusercontent.com/11717564/120640403-bcee9400-c472-11eb-95bf-7280dc974f83.png)

**Additional context**
The problem is especially when having dynamic components, e.g. a table (delegates is preferred here) but also when using routing to change pages. 

Tippy.js has a .destroy() method: https://atomiks.github.io/tippyjs/v6/methods/#destroy

**Comment by farengeyt451** [comment]
Hi @bjarketrux! Thank you for finding this bug and creating issue. I will try to fix it.

**Comment by farengeyt451** [comment]
Fixed on `v3.0.1`
