### ISSUE TITLE
Show/Hide tooltip based on content inside element

### ISSUE THREAD

**Issue by bhawin-boom** [farengeyt451/ngx-tippy-wrapper#21]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when the I have to show conditional tooltip 
`<div ngxTippy [tippyProps]="{
  arrow: true,
  createPopperInstanceOnInit: true,
  content:'Hello',
  placement: 'top'
}">Hello</div>
`

This is the code I am using to render tooltip, 

What I want is the tooltip to show only when the content inside the div is large .
like "hello. this is a very large tooltip ..."
not when the content inside div is small like 'Hello'.

Note: I don't want to use *ngIf in my angular code .

**Comment by farengeyt451** [comment]
```ts
...
export class AppComponent implements OnInit {
  public readonly content: string = 'Tooltip content'
  
  ...
}
```

```html
<div
  [ngxTippy]="content.length > 10 ? content : null"
  [tippyProps]="{ arrow: true, placement: 'top' }"
>
  {{ content }}
</div>
```

[Covered in the README]( https://github.com/farengeyt451/ngx-tippy-wrapper#initializing-on-condition)

**Comment by bhawin-boom** [comment]
Well , I don not know the content length , I just want to show tooltip when the content inside it is coming in next line or you can say more then 1 line .

**Comment by farengeyt451** [comment]
@bhawin-boom  This feature is not implemented. You should write own logic for conditional tooltip render.
