### ISSUE TITLE
Update to Angular 13

### ISSUE THREAD

**Issue by hadrien-toma** [farengeyt451/ngx-tippy-wrapper#28]
It would be nice to support Angular 13 :blush: 

Thank you very much for the work already done!

**Comment by farengeyt451** [comment]
Hey @hadrien-toma! Thank you for feedback. I will update plugin), but I can not be sure in timing.

**Comment by Swindyyy** [comment]
Are there any issues with using the current version with Angular 13? 

I am using 13 at the moment and can only get the base [data](https://github.com/farengeyt451/ngx-tippy-wrapper#you-can-pass-tooltip-content-through) attribute, and just for the sake of my sanity I'm just posting here to see if anyone has it working normally with 13

Anyhow, thanks for the plugin and I'm looking forward to the update :)

**Comment by farengeyt451** [comment]
v5.x.x
