### ISSUE TITLE
No provider for InjectionToken NGX_TIPPY_MESSAGES!

### ISSUE THREAD

**Issue by mbonnevalle** [farengeyt451/ngx-tippy-wrapper#31]
**Describe the bug**
I try to add tippy to my project but it doesn't work 

**Expected behavior**
I expeted to get a context menu with the text = Test (as show in the screenshot)

**Screenshots**
![image](https://user-images.githubusercontent.com/83005196/168614632-728f0872-40b0-4ee0-894b-bb5d90160f77.png)

![image](https://user-images.githubusercontent.com/83005196/168614543-f33950cb-ceb1-4984-b414-fd5e66a2f07f.png)

![image](https://user-images.githubusercontent.com/83005196/168614818-9048e69c-c5d0-4320-beb3-ab2977ed2642.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows 10
- Browser [e.g. chrome, safari] chrome
- Version [e.g. 22] latest

**Environment context**

- Angular version ~13.3.4
- TypeScript version ~4.5.2
- ngx-tippy-wrapper version: ^5.0.1

**Comment by farengeyt451** [comment]
@mbonnevalle pls recreate the issue on codesandbox

**Comment by mbonnevalle** [comment]
Ok the issue is when you didn't add the module on the main app module file but only on a module

**Comment by rockyahmed** [comment]
Any Update about this issue Angular 14

**Comment by farengeyt451** [comment]
Fixed in v[5.0.2](https://www.npmjs.com/package/ngx-tippy-wrapper/v/5.0.2)
