### ISSUE TITLE
Injected tooltip with InnerHtml 

### ISSUE THREAD

**Issue by devglrd** [farengeyt451/ngx-tippy-wrapper#51]
Hi all, 

I try to implemente a tooltip but provide dynamicly with injected html content like : 

`
public injectedText = this.sanitaze.bypassSecurityTrustHtml('A <span ngxTippy tippyName="bionic_beaver_2">tooltip here</span>');
`

`<div class="mt-3 mb-4" [innerHTML]="injectedText"></div>`

And in the ng After View Init

`this.tippyService.setContent('bionic_beaver_2', 'Tooltip content via service');`

But this doesnt work, i got `Instance with name 'bionic_beaver_2' does not exist` error.

I don't know if there is a way to do it.

**Comment by farengeyt451** [comment]
@devglrd For me seems it's not possible
