### ISSUE TITLE
Possibility pass ng-template ref as template ?

### ISSUE THREAD

**Issue by Murena7** [farengeyt451/ngx-tippy-wrapper#8]
Hi - how i can pass ng-template ref as template ?

**Comment by farengeyt451** [comment]
Hi @Murena7, this feature is not available for now. I think about this feature too, i will try to implement this on possibility.

**Comment by Murena7** [comment]
> Hi @Murena7, this feature is not available for now. I think about this feature too, i will try to implement this on possibility.

Thanks!
