### ISSUE TITLE
Correct way to use followCursor option ?

### ISSUE THREAD

**Issue by Murena7** [farengeyt451/ngx-tippy-wrapper#9]
Hi - please explain how i can use followCursor option ? When i simple set followCursor: true in [tippyProps] - this didn't work. Thanks.

**Comment by farengeyt451** [comment]
@Murena7 For this purpose you should import `followCursor` plugin from `tippy.js` and pass it to `plugins` props like this:

```
import { followCursor } from 'tippy.js';

tippyProps: NgxTippyProps = {
  followCursor: true,
  plugins: [followCursor],
};
```

Ref to Tippy.js docs https://atomiks.github.io/tippyjs/v6/all-props/#followcursor

**Comment by farengeyt451** [comment]
Covered in demo, `Plugins usage` section.
